{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "EmployeePayroll",
        "description": "This app is build for EmployeePayroll",
        "license" : {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        }        
    },
    "host": "localhost:3000",
    "tags": [
        {
            "name": "EmployeePayroll",
            "description": "API for registration"
        }
    ],
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/register": {
            "post": {
                "tags": ["registration"],
                "description": "Create new registration",
                "parameters": [
                    {
                        "name": "registration",
                        "in": "body",
                        "description": "Create new registration",
                        "schema": { 
                            "$ref": "#/definitions/registration"
                        }
                    }
                ],

                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "registration successfully"
                    },
                    "500": {
                        "description": "server-error or alredy exist"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": ["Login"],
                "description": "Login Employee",
                "parameters": [
                    {
                        "name": "Login",
                        "in": "body",
                        "description": "Employee want to login",
                        "schema": {
                            "$ref": "#/definitions/loginemployeepayroll"
                        }
                    }
                ],
    
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "ok or Invalid email or password"
                    }
                }
            }
        },
        "/createEmployee": {
            "post": {
                "tags": [
                    "Create Employee"
                ],
                "description": "Creating a employee",
                "parameters": [
                    {
                        "in": "header",
                        "name": "Authorization",
                        "description": "Token for vaidation",
                        "schema": {
                            "type": "string"
                           
                        }
                    },
                    {
                        "name": "create employee",
                        "in": "body",
                        "description": "employee body",
                        "schema": {
                            "$ref": "#/definitions/employee"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "schema": {
                    "$ref": "#/definitions/employee"
                },
                "responses": {
                    "200": {
                        "description": "Employee Created Successfully"
                    },
                    "401": {
                        "description": "Your token has expiered"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/getall": {
            "get": {
                "tags": [
                    "Get All Employee"
                ],
                "description": "Get all Employee",
                "parameters": [
                    {
                        "in": "header",
                        "name": "Authorization",
                        "description": "Token for vaidation",
                        "schema": {
                            "type": "string"
                            
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                
                "responses": {
                    "200": {
                        "description": "Get All Employee Successfully"
                    },
                    "401": {
                        "description": "Your token has expiered Or Enter Valid Token"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/getbyid/{id}": {
            "get": {
                "tags": [
                    "Get Employee By Id"
                ],
                "description": "Get employee by ID",
                "parameters": [
                    {
                        "in": "header",
                        "name": "Authorization",
                        "description": "Token for vaidation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id of employee you want to Get",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Employee Found Successfully"
                    },
                    "401": {
                        "description": "Your token has expiered Or Enter Valid Token"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/update": {
            "put": {
                "tags": [
                    "Update Employee By Id"
                ],
                "description": "put employee by ID",
                "parameters": [
                    {
                        "in": "header",
                        "name": "Authorization",
                        "description": "Token for vaidation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "update employee",
                        "in": "body",
                        "description": "employee body",
                        "schema": {
                            "$ref": "#/definitions/updateemployee"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Employee Updated Successfully or Duplicate Email"
                    },
                    "401": {
                        "description": "Your token has expiered Or Enter Valid Token"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/delete": {
            "delete": {
                "tags": [
                    "Delete Employee By Id"
                ],
                "description": "delete employee by ID",
                "parameters": [
                    {
                        "in": "header",
                        "name": "Authorization",
                        "description": "Token for vaidation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "delete employee",
                        "in": "body",
                        "description": "employee body",
                        "schema": {
                            "$ref": "#/definitions/deleteemployee"
                        }
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Employee Deleted succesfully"
                    },
                    "401": {
                        "description": "Your token has expiered Or Enter Valid Token"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }
    },
    "definitions": {
        "registration": {        
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "designation": {
                    "type": "string"
                },
                "joningdate": {
                    "type": "string"
                }
            },
            "example": {
                "email":"test@gmail.com",
                "password": "password",
                "firstName":"firstname",
                "lastName":"lastname",
                "designation":"developer",
                "joningdate":"2021-10-28"
            }
        },
        "loginemployeepayroll": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            },
            "example": {
                "email":"new@gmail.com",
                "password":"password1"
            }
        },
        "employee": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "designation": {
                    "type": "string"
                },
                "joningdate": {
                    "type": "string"
                }
            },
            "example": {
                "email":"test@gmail.com",
                "password": "password",
                "firstName":"firstname",
                "lastName":"lastname",
                "designation":"developer",
                "joningdate":"2021-10-28"
            }
        },
        "updateemployee": {
            "type": "object",
            "properties": {
                "id":{
                    "type":"string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "designation": {
                    "type": "string"
                },
                "joningdate": {
                    "type": "string"
                }
            },
            "example": {
                "id":"52",
                "email":"test@gmail.com",
                "password": "password",
                "firstName":"firstname",
                "lastName":"lastname",
                "designation":"developer",
                "joningdate":"2021-10-28"
            }
        },
        "deleteemployee": {
            "type": "object",
            "properties": {
                "id":{
                    "type":"string"
                }
            },
            "example": {
                "id":"37"
            }
        }
    }
} 